// TODO: replace all with real API calls when backend is ready

import type { ServiceCard, TimelineItem, Document, LifeEvent, User, NotificationSetting } from "@/types";

export const mockUser: User = {
  id: "usr_001",
  name: "Budi Santoso",
  nik: "3174012345678901",
  email: "budi.santoso@email.com",
  phone: "+62 812-3456-7890",
  address: "Jl. Kebon Jeruk No. 12, Jakarta Barat, DKI Jakarta 11530",
  birthDate: "1990-03-15",
};

export const mockServices: ServiceCard[] = [
  {
    id: "pajak",
    name: "Pajak",
    icon: "Receipt",
    status: "warning",
    description: "Pajak Penghasilan Tahunan",
    dueDate: "2026-03-31",
    lastUpdated: "2026-01-10",
  },
  {
    id: "bpjs",
    name: "BPJS Kesehatan",
    icon: "HeartPulse",
    status: "active",
    description: "Kelas 1 — Keluarga",
    dueDate: "2026-08-01",
    lastUpdated: "2026-07-01",
  },
  {
    id: "sim",
    name: "SIM",
    icon: "Car",
    status: "active",
    description: "SIM A — berlaku hingga 2028",
    dueDate: "2028-05-22",
    lastUpdated: "2024-05-22",
  },
  {
    id: "stnk",
    name: "STNK",
    icon: "FileText",
    status: "expired",
    description: "Honda Brio B 1234 ABC",
    dueDate: "2026-06-15",
    lastUpdated: "2025-06-15",
  },
  {
    id: "paspor",
    name: "Paspor",
    icon: "BookOpen",
    status: "active",
    description: "Paspor Biasa — berlaku 2029",
    dueDate: "2029-11-08",
    lastUpdated: "2024-11-08",
  },
  {
    id: "pln",
    name: "PLN",
    icon: "Zap",
    status: "warning",
    description: "Tagihan Juli 2026",
    dueDate: "2026-07-30",
    lastUpdated: "2026-07-01",
  },
  {
    id: "pdam",
    name: "PDAM",
    icon: "Droplets",
    status: "active",
    description: "Tagihan Juli 2026 — Lunas",
    dueDate: "2026-08-20",
    lastUpdated: "2026-07-05",
  },
];

export const mockTimeline: TimelineItem[] = [
  {
    id: "tl_001",
    service: "STNK",
    title: "STNK Honda Brio sudah kedaluwarsa",
    date: "2026-06-15",
    status: "expired",
    description: "STNK kendaraan Anda sudah melewati batas waktu perpanjangan. Segera perpanjang ke Samsat terdekat.",
    daysUntil: -42,
  },
  {
    id: "tl_002",
    service: "Pajak",
    title: "Batas akhir Pajak Penghasilan",
    date: "2026-08-31",
    status: "warning",
    description: "Pajak Penghasilan tahunan Anda mendekati jatuh tempo. Lapor melalui DJP Online.",
    daysUntil: 35,
  },
  {
    id: "tl_003",
    service: "PLN",
    title: "Tagihan PLN Juli 2026",
    date: "2026-07-30",
    status: "warning",
    description: "Tagihan listrik bulan Juli belum dibayar. Bayar melalui PLN Mobile atau transfer bank.",
    daysUntil: 3,
  },
  {
    id: "tl_004",
    service: "BPJS",
    title: "Iuran BPJS Agustus 2026",
    date: "2026-08-01",
    status: "active",
    description: "Iuran BPJS Kesehatan untuk bulan Agustus. Autodebet aktif.",
    daysUntil: 5,
  },
  {
    id: "tl_005",
    service: "SIM",
    title: "Perpanjangan SIM A",
    date: "2028-05-22",
    status: "active",
    description: "SIM A Anda masih berlaku hingga 2028. Tidak ada tindakan yang diperlukan saat ini.",
    daysUntil: 664,
  },
  {
    id: "tl_006",
    service: "Paspor",
    title: "Perpanjangan Paspor",
    date: "2029-11-08",
    status: "active",
    description: "Paspor Anda masih berlaku hingga 2029.",
    daysUntil: 1200,
  },
];

export const mockDocuments: Document[] = [
  {
    id: "doc_001",
    name: "KTP_Budi_Santoso.pdf",
    type: "PDF",
    size: "2.4 MB",
    uploadedAt: "2026-01-15",
    category: "Identitas",
  },
  {
    id: "doc_002",
    name: "STNK_Honda_Brio.pdf",
    type: "PDF",
    size: "1.1 MB",
    uploadedAt: "2026-03-20",
    category: "Kendaraan",
  },
  {
    id: "doc_003",
    name: "NPWP_Budi_Santoso.jpg",
    type: "JPG",
    size: "856 KB",
    uploadedAt: "2025-12-01",
    category: "Pajak",
  },
  {
    id: "doc_004",
    name: "Kartu_BPJS_Kesehatan.jpg",
    type: "JPG",
    size: "420 KB",
    uploadedAt: "2026-02-10",
    category: "Kesehatan",
  },
  {
    id: "doc_005",
    name: "Paspor_Scan.pdf",
    type: "PDF",
    size: "3.2 MB",
    uploadedAt: "2024-11-15",
    category: "Perjalanan",
  },
];

export const mockLifeEvents: LifeEvent[] = [
  {
    id: "le_001",
    title: "Menikah",
    description: "Panduan lengkap administrasi pernikahan di Indonesia.",
    icon: "Heart",
    category: "Keluarga",
    steps: [
      "Daftar di KUA setempat",
      "Siapkan dokumen: KTP, KK, Akta Lahir",
      "Update status di Dukcapil",
      "Perbarui data BPJS",
      "Update data pajak (NPWP gabungan opsional)",
    ],
  },
  {
    id: "le_002",
    title: "Memiliki Anak",
    description: "Langkah-langkah mengurus administrasi kelahiran.",
    icon: "Baby",
    category: "Keluarga",
    steps: [
      "Urus Akta Kelahiran di Dukcapil (maks. 60 hari)",
      "Tambahkan anak ke Kartu Keluarga",
      "Daftarkan ke BPJS Kesehatan",
      "Buat NIK anak",
      "Daftarkan ke program imunisasi Puskesmas",
    ],
  },
  {
    id: "le_003",
    title: "Pindah Rumah",
    description: "Checklist administrasi pindah domisili.",
    icon: "Home",
    category: "Domisili",
    steps: [
      "Urus Surat Keterangan Pindah di kelurahan asal",
      "Lapor ke kelurahan tujuan",
      "Update Kartu Keluarga di Dukcapil",
      "Ganti alamat KTP (E-KTP baru)",
      "Update alamat di BPJS, PLN, PDAM, Bank",
    ],
  },
  {
    id: "le_004",
    title: "Membuka Usaha",
    description: "Panduan legal dan administrasi memulai bisnis.",
    icon: "Briefcase",
    category: "Bisnis",
    steps: [
      "Pilih badan usaha (PT, CV, UD, dll.)",
      "Daftarkan di Kemenkumham (untuk PT)",
      "Urus NPWP Badan",
      "Daftarkan NIB di OSS (oss.go.id)",
      "Urus izin usaha sesuai bidang",
    ],
  },
];

export const mockNotificationSettings: NotificationSetting[] = [
  {
    id: "notif_stnk",
    label: "Perpanjangan STNK",
    description: "Ingatkan 30 hari sebelum jatuh tempo",
    enabled: true,
  },
  {
    id: "notif_sim",
    label: "Perpanjangan SIM",
    description: "Ingatkan 60 hari sebelum jatuh tempo",
    enabled: true,
  },
  {
    id: "notif_pajak",
    label: "Batas Lapor Pajak",
    description: "Ingatkan 30 hari sebelum deadline",
    enabled: true,
  },
  {
    id: "notif_bpjs",
    label: "Iuran BPJS",
    description: "Ingatkan 5 hari sebelum jatuh tempo",
    enabled: false,
  },
  {
    id: "notif_pln",
    label: "Tagihan PLN",
    description: "Ingatkan 7 hari sebelum jatuh tempo",
    enabled: true,
  },
];
